[features]
seeds = false
[programs.localnet]
solcbd = "9ULGJGMCU3AapbNuCfV4aryAV5w5NYdAaJxSgvjMw21Y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/madhurdixit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
